#pragma once

#ifdef RGBLIGHT_ENABLE
#    define RGBLIGHT_EFFECT_BREATHING
#    define RGBLIGHT_EFFECT_RAINBOW_MOOD
#    define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#    define RGBLIGHT_EFFECT_SNAKE
#    define RGBLIGHT_EFFECT_KNIGHT
#    define RGBLIGHT_EFFECT_CHRISTMAS
#    define RGBLIGHT_EFFECT_STATIC_GRADIENT
#    define RGBLIGHT_EFFECT_RGB_TEST
#    define RGBLIGHT_EFFECT_ALTERNATING
#    define RGBLIGHT_EFFECT_TWINKLE
#endif

//タップとホールドの判定時間(100で0.1秒)
#define TAP_CODE_DELAY 100

//トラックボールの有効化
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
//オートマウスレイヤーのレイヤー指定(0から数える)
#define AUTO_MOUSE_DEFAULT_LAYER 5
